# Generated by Django 3.0.3 on 2021-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20211019_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'inventario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto'},
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
