# Generated by Django 3.0.3 on 2021-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('tipo_movimiento', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField()),
                ('tabla', models.CharField(max_length=20)),
                ('registro_id', models.IntegerField()),
                ('padre_id', models.IntegerField(null=True)),
                ('obj_old', models.CharField(max_length=2000)),
                ('obj_new', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'bitacora',
            },
        ),
    ]
