# Generated by Django 3.0.3 on 2021-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_id', models.IntegerField()),
                ('puntos', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dpi', models.CharField(max_length=15, null=True)),
                ('nit', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=8, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'entidades',
                'db_table': 'entidades',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'proveedores',
                'db_table': 'proveedores',
            },
        ),
    ]
