# Generated by Django 3.0.3 on 2021-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'entidad'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'proveedor'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='entidad',
            table='entidad',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
    ]
