# Generated by Django 3.0.3 on 2021-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_id', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('flg_activo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'sucursales',
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal_id', models.IntegerField()),
                ('empleado_id', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'turnos',
                'db_table': 'turnos',
            },
        ),
    ]
