# Generated by Django 3.0.3 on 2021-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'empleado'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'sucursal'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'turno'},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
        migrations.AlterModelTable(
            name='turno',
            table='turno',
        ),
    ]
