# Generated by Django 3.0.3 on 2021-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_id', models.IntegerField()),
                ('sucursal_id', models.IntegerField()),
                ('estado_compra_id', models.IntegerField()),
                ('documento', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'compras',
                'db_table': 'compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'compra_detalles',
                'db_table': 'compra_detalles',
            },
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'compra_estados',
                'db_table': 'compra_estados',
            },
        ),
    ]
