# Generated by Django 3.0.3 on 2021-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'compra'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'detalle_compra'},
        ),
        migrations.AlterModelOptions(
            name='estadocompra',
            options={'verbose_name': 'estado_compra'},
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compra',
        ),
        migrations.AlterModelTable(
            name='detallecompra',
            table='detalle_compra',
        ),
        migrations.AlterModelTable(
            name='estadocompra',
            table='estado_compra',
        ),
    ]
