# Generated by Django 3.0.3 on 2021-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_id', models.IntegerField()),
                ('producto_id', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'venta_detalles',
                'db_table': 'venta_detalles',
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'venta_estados',
                'db_table': 'venta_estados',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'metodos_pago',
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField()),
                ('emp_cajero_id', models.IntegerField()),
                ('sucursal_id', models.IntegerField()),
                ('metodo_pago_id', models.IntegerField()),
                ('estado_venta_id', models.IntegerField()),
                ('documento', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'ventas',
                'db_table': 'ventas',
            },
        ),
    ]
