# Generated by Django 3.0.3 on 2021-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'detalle_venta'},
        ),
        migrations.AlterModelOptions(
            name='estadoventa',
            options={'verbose_name': 'estado_venta'},
        ),
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'metodo_pago'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta'},
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
        migrations.AlterModelTable(
            name='estadoventa',
            table='estado_venta',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='metodo_pago',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
    ]
