# Generated by Django 3.0.3 on 2021-10-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acceso',
            table='rol_acceso',
        ),
        migrations.AlterModelTable(
            name='operacion',
            table='operacion',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='rolusuario',
            table='rol_usuario',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
